#!/bin/bash
apt-get update && apt-get upgrade -y
apt-get install curl -y
apt-get install apache2 -y
apt-get install php5 libapache2-mod-php5 php5-mcrypt -y
service apache2 restart
apt-get install mysql-server php5-mysql
mysql_install_db
mysql_secure_installation
apt-get install phpmyadmin -y
php5enmod mcrypt
service apache2 restart
ln -s /usr/share/phpmyadmin /var/www/html/phpmyadmin
apt-get install libssh2-1-dev libssh2-php -y
php -m |grep ssh2
service apache2 restart
mysql -h localhost -u root -p03101994 -e "CREATE DATABASE ssh"
service apache2 restart
wget -O painel.zip https://www.dropbox.com/s/f2yo8u7b42imysv/painelssh.zip?dl=0 && mv painel.zip /var/www/html
cd /var/www/html
apt-get install unzip -y
unzip painel.zip
rm painel.zip
nano /var/www/html/pages/system/pass.php
service apache2 restart
nano /etc/crontab
dpkg-reconfigure tzdata
service apache2 restart
clear
reboot
